name: JoseF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Limpiar cache e inconsistencias
        run: |
          rm -f package-lock.json
          npm cache clean --force

      - name: Corregir dependencias mal escritas (standart → standard)
        run: |
          sed -i 's/"standart"/"standard"/g' package.json

      - name: Instalar dependencias (reconstruye lock file)
        run: npm install --legacy-peer-deps

      - name: Compilar proyecto
        run: npm run build
